export const CLAUDE_RUNTIME_MODELS = [
  {
    id: "claude-fable-5",
    name: "Claude Fable 5 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
    contextWindow: 1_000_000,
    maxTokens: 128_000,
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
    contextWindow: 1_000_000,
    maxTokens: 128_000,
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
    contextWindow: 1_000_000,
    maxTokens: 128_000,
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
    contextWindow: 1_000_000,
    maxTokens: 128_000,
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
    contextWindow: 1_000_000,
    maxTokens: 64_000,
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (Agent SDK)",
    reasoning: true,
    input: ["text", "image"] as const,
    cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
    contextWindow: 200_000,
    maxTokens: 64_000,
  },
] as const;
